version: 2
updates:
  - package-ecosystem: "bun"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      svelte:
        patterns:
          - "svelte"
          - "svelte-check"
          - "@sveltejs/*"
          - "mdsvex"
          - "vite"
      fonts:
        patterns:
          - "@fontsource/*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
